# Constants
RAW_SAMPLES = 256
NUM_RESTARTS = 16
BATCH_LIMIT = 4
QNEHVI_RAW_SAMPLES = 512
QNEHVI_BATCH_LIMIT = 2
NUM_TRUE_UTIL_SAMPLES = 512
NUM_PAREGO_SAMPLES = 256
NUM_LEARN_PREF_SAMPLES_UNEIPM = 256
NUM_LEARN_PREF_SAMPLE_UNEI = 8
NUM_LEARN_OUTCOME_SAMPLE_UNEI = 32
NUM_EVAL_PREF_SAMPLES = 16
NUM_EVAL_OUTCOME_SAMPLES = 32
FTOL = 1e-5
